expose:
  type: ingress
  tls:
    enabled: true
  ingress:
    hosts:
      core: registry.image.local.com
      notary: registry.image.local.com
    annotations:
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
        
externalURL: registry.image.local.com

persistence:
  enabled: true
  persistentvolumeclaim:
    registry:
      storageclass: "harbor-registry"
      size: 200Gi
    chartmuseum:
      storageclass: "harbor-chartmuseum"
      size: 10Gi
    jobservice:
      storageclass: "harbor-jobservice"
      size: 2Gi
    database:
      storageclass: "harbor-database"
      size: 2Gi
    redis:
      storageclass: "harbor-redis"
      size: 2Gi
    trivy:
      storageclass: "harbor-trivy"
      size: 20Gi